version: '2'
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    networks:
      default:
        aliases:
          - db

  walletmgr:
    container_name: walletmgr
    networks:
      default:
        aliases:
          - walletmgr
    build:
      context: ../
      dockerfile: .deploy/walletmgr/Dockerfile
    hostname: walletmgr
    depends_on:
      - "db"
    ports:
      - "8080:8080"

networks:
  default: